### PR TITLE
add tunnel-network config

### PR DESCRIPTION
**Pull request by jamesbeedy**
Adds configurable tunnel network address space.

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
Hi James

What's the reason that you want to configure this network?

I'm very hesitant to adding more config options, I want to see if we can
make the Charm figure out what tunnel-network it should use.

**Comment by jamesbeedy** [comment]
I was thinking there might be issues if you are using multiple vpn connections, and your host gets multiple interfaces with 10.200.200 ips, but I don't think that matters because the routing rules specify the interface over which the traffic should pass You can disregard this. Thanks

**Comment by merlijn-sebrechts** [comment]
This is so freaky! We also stumbled upon this issue tuesday. Juju ssh
becomes confused when you connect to two vpn's at the same time because it
prefers the 10.200.. ip to ssh to the unit, but then you have two machines
with that ip. Sander is working on a fix for this, the charm will pick a
random unused network range. So each vpn will have a unique network.

**Comment by merlijn-sebrechts** [comment]
PS: the patch to use a random available network for the tunnel has just landed in beta: https://jujucharms.com/u/tengu-team/openvpn/6

Want to try it out?

**Comment by jamesbeedy** [comment]
Nice!! I'll give it a pounding here in a few!

**Pull request closed without merging**
