### PR TITLE
specify network and netmask as config for testing

### PR DESCRIPTION
**Pull request by jamesbeedy**
Add 'private-network' config and render directly into init.pp.

### CODE REVIEW

**Comment by jamesbeedy** [comment]
@galgalesh This seems to be doing the trick. Now if only we could generate them dynamically.

Edit: I was over zealous there too ... totally isn't pushing the route still ....

I think the internal_networks generation might need some help because no networks are making it into the push config currently. Thats why the route isn't being pushed.

But it seems even when the route is pushed it still wont forward traffic to the private address space

**Comment by jamesbeedy** [comment]
Aha! It is the difference between "route 172.100.0.0/24" and "route 172.100.0.0 255.255.255.0".

Only the latter is valid.

so

```yaml
# openvpn.yaml
openvpn:
  push-default-gateway: false
  private-network: "172.31.0.0 255.255.255.0"
```
^ (using private address space of 172.31.0.0) ^ config, with the changes in this PR make the routing/forwarding functionality work correctly!

Now we just need to fix the helper functions to actually pick up the private network and then we won't need these changes I'm thinking.

Possibly a config might actually be the best way forward here, then you could forward to any subnet in your vpc if you wanted.

**Comment by merlijn-sebrechts** [comment]
@jamesbeedy 

Can you show the output of "route -n" and "ifconfig" on the openvpn server? I'd like to find out why our helper functions don't pick this network up..

**Comment by jamesbeedy** [comment]
@galgalesh 

`route -n` <- http://paste.ubuntu.com/24929694/
`ifconfig` <- http://paste.ubuntu.com/24929698/

**Comment by merlijn-sebrechts** [comment]
@jamesbeedy 

I can't find the `172.31.0.0 255.255.255.0` network in your output of `ifconfig` and `route`. Just to confirm, that is indeed the network that should be pushed in your case?

If that's indeed the case, then there is no way for the helpers to "pick up that network", so then the only solution is adding this config option.

**Comment by merlijn-sebrechts** [comment]
Closing this PR.

As explained in https://github.com/tengu-team/layer-openvpn/issues/9#issuecomment-346994880, the charm now pushes all routes of the machine the VPN server is running on to the clients.

I'm very hesitant to introduce this config option because I feel as if this tries to fix network/infra-level issues at the application level: the charm will now do the right thing unless the routes aren't configured correctly on the VPN server machine. You can now fix those issues at the network/infra level: just add a static route on the VPN server host, reconfigure the charm and that route will be pushed to all clients.

**Pull request closed without merging**
